---
- name: Prepara nodi Proxmox (install prereq)
  hosts: all
  become: true
  tags: prereq

  tasks:
    - name: Installa NFS client
      apt:
        name: nfs-common
        state: present

    - name: Installa ZFS utils
      apt:
        name: zfsutils-linux
        state: present

- name: Definisci storage in Proxmox
  hosts: all
  gather_facts: false
  become: true
  tags: define_storage

  roles:
    - role: lae.proxmox
      vars:
        pve_group: proxmox_cluster
        pve_cluster_enabled: true
        pve_cluster_clustername: pve-cluster

        pve_storages:
          # storage ZFS locale rimane per i dataset di root
          - name: zfs-local
            type: zfspool
            pool: rpool/data
            content:
              - images
              - rootdir
            sparse: true

          # NFS condiviso
          - name: nfs-shared
            type: nfs
            server: 192.168.0.240
            export: /export/proxmox
            options: vers=4
            content:
              - images
              - rootdir
              - iso

        pve_repo: pve-no-subscription
        pve_extra_packages: []

- name: Verifica che lo storage sia online
  hosts: pve_cluster
  gather_facts: no
  become: true
  tags: verify_storage

  tasks:
    - name: Controlla che export NFS sia visibile
      command: showmount -e 192.168.0.240
      register: exports

    - name: Fallisci se non vedo /export/proxmox
      fail:
        msg: "L'export NFS /export/proxmox non è raggiungibile da {{ inventory_hostname }}"
      when: "'/export/proxmox' not in exports.stdout"

    - name: Controlla che Proxmox veda lo storage
      command: pvesm status
      register: status

    - name: Fallisci se nfs-shared non è in pvesm status
      fail:
        msg: "Lo storage nfs-shared non è in linea su {{ inventory_hostname }}"
      when: "'nfs-shared' not in status.stdout"

    - name: Forza il mount di nfs-shared
      command: pvesm mount nfs-shared
      register: mount_nfs
      failed_when:
        - "( mount_nfs.rc != 0 ) and ('already mounted' not in mount_nfs.stderr)"

    - name: Attendi che Proxmox veda lo storage online
      command: pvesm status
      register: pvesm_status
      until: "'nfs-shared' in pvesm_status.stdout and 'online' in pvesm_status.stdout"
      retries: 5
      delay: 5
