- name: Configure /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
  when: ansible_default_ipv4.address is defined
  register: hosts_changed

- name: Configure DNS servers
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      {% for dns in dns_servers %}
      nameserver {{ dns }}
      {% endfor %}
    mode: "0644"

