talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: clA-cluster-a
endpoint: https://192.168.0.230:6443

clusterPodNets:
  - 10.14.0.0/16
clusterSvcNets:
  - 10.15.0.0/16

additionalApiServerCertSans:
  - 192.168.0.230
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.0.230
  - 127.0.0.1

nodes:
  - hostname: clA-cp01
    controlPlane: true
    ipAddress: 192.168.0.110
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:00:01"
        dhcp: false
        vip:
          ip: 192.168.0.230

  - hostname: clA-cp02
    controlPlane: true
    ipAddress: 192.168.0.111
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:00:02"
        dhcp: false
        vip:
          ip: 192.168.0.230

  - hostname: clA-cp03
    controlPlane: true
    ipAddress: 192.168.0.112
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:00:03"
        dhcp: false
        vip:
          ip: 192.168.0.230

  - hostname: clA-wk01
    controlPlane: false
    ipAddress: 192.168.0.113
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:10:01"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
              - SUBSYSTEM=="drm", KERNEL=="card*",    GROUP="44", MODE="0660"

  - hostname: clA-wk02
    controlPlane: false
    ipAddress: 192.168.0.114
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:10:02"
        dhcp: false

  - hostname: clA-wk03
    controlPlane: false
    ipAddress: 192.168.0.115
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:00:10:03"
        dhcp: false

patches:
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
