talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: clc
endpoint: https://192.168.0.130:6443

clusterPodNets:
  - 10.18.0.0/16
clusterSvcNets:
  - 10.19.0.0/16

additionalApiServerCertSans:
  - 192.168.0.232
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.0.232
  - 127.0.0.1


# Centralized patches for network, time and kubelet
patches:
  # Machine-level patches: DNS, NTP and kubelet certificate rotation
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      time:
        disabled: false
        servers:
          - time.cloudflare.com
          - time.google.com


controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

nodes:
  - hostname: clc-cp01
    controlPlane: true
    ipAddress: 192.168.0.130
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:00:01"
        dhcp: false
        vip:
          ip: 192.168.0.232

  - hostname: clc-cp02
    controlPlane: true
    ipAddress: 192.168.0.131
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:00:02"
        dhcp: false
        vip:
          ip: 192.168.0.232

  - hostname: clc-cp03
    controlPlane: true
    ipAddress: 192.168.0.132
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:00:03"
        dhcp: false
        vip:
          ip: 192.168.0.232

  - hostname: clc-wk01
    controlPlane: false
    ipAddress: 192.168.0.133
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:10:01"
        dhcp: false

  - hostname: clc-wk02
    controlPlane: false
    ipAddress: 192.168.0.134
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:10:02"
        dhcp: false

  - hostname: clc-wk03
    controlPlane: false
    ipAddress: 192.168.0.135
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:02:10:03"
        dhcp: false

