talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: clc
endpoint: https://192.168.0.232:6443   # Talos endpoint (direct individual node IPs will be used)

clusterPodNets:
  - 10.18.0.0/16
clusterSvcNets:
  - 10.19.0.0/16

additionalApiServerCertSans:
  - 192.168.0.232  # VIP
  - 192.168.0.130
  - 192.168.0.131
  - 192.168.0.132
  - 127.0.0.1

additionalMachineCertSans:
  - 192.168.0.232  # VIP
  - 192.168.0.130
  - 192.168.0.131
  - 192.168.0.132
  - 127.0.0.1

patches:
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
      time:
        disabled: false
        servers:
          - time.cloudflare.com
          - time.google.com
      kubelet:
        extraArgs:
          authorization-mode: AlwaysAllow

cluster:
  discovery:
    enabled: false
    registries:
      service:
        disabled: true

controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: flannel
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

nodes:
  - hostname: clc-cp01
    controlPlane: true
    ipAddress: 192.168.0.130
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false

  - hostname: clc-cp02
    controlPlane: true
    ipAddress: 192.168.0.131
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false

  - hostname: clc-cp03
    controlPlane: true
    ipAddress: 192.168.0.132
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false

  - hostname: clc-wk01
    controlPlane: false
    ipAddress: 192.168.0.133
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false

  - hostname: clc-wk02
    controlPlane: false
    ipAddress: 192.168.0.134
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: false
