# talos-cluster-c.yaml
talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: talos-cluster-c
endpoint: https://192.168.0.202:6443

clusterPodNets:
  - 10.34.0.0/16
clusterSvcNets:
  - 10.35.0.0/16

additionalApiServerCertSans:
  - 192.168.0.202
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.0.202
  - 127.0.0.1

nodes:
  - hostname: talos-master-01
    controlPlane: true
    ipAddress: 192.168.0.176
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false
        vip:
          ip: 192.168.0.202

  - hostname: talos-master-02
    controlPlane: true
    ipAddress: 192.168.0.177
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false
        vip:
          ip: 192.168.0.202

  - hostname: talos-master-03
    controlPlane: true
    ipAddress: 192.168.0.178
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false
        vip:
          ip: 192.168.0.202

  - hostname: talos-worker-01
    controlPlane: false
    ipAddress: 192.168.0.185
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

  - hostname: talos-worker-02
    controlPlane: false
    ipAddress: 192.168.0.186
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false

  - hostname: talos-worker-03
    controlPlane: false
    ipAddress: 192.168.0.187
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "68:1d:ef:50:5f:e7"
        dhcp: false

patches:
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
