# talos-cluster-a.yaml
talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: talos-cluster-a
endpoint: https://192.168.0.200:6443

clusterPodNets:
  - 10.14.0.0/16
clusterSvcNets:
  - 10.15.0.0/16

additionalApiServerCertSans:
  - 192.168.0.200
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.0.200
  - 127.0.0.1

nodes:
  - hostname: talos-master-01
    controlPlane: true
    ipAddress: 192.168.0.170
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false
        vip:
          ip: 192.168.0.200

  - hostname: talos-master-02
    controlPlane: true
    ipAddress: 192.168.0.171
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false
        vip:
          ip: 192.168.0.200

  - hostname: talos-master-03
    controlPlane: true
    ipAddress: 192.168.0.172
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false
        vip:
          ip: 192.168.0.200

  - hostname: talos-worker-01
    controlPlane: false
    ipAddress: 192.168.0.180
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
              - SUBSYSTEM=="drm", KERNEL=="card*",    GROUP="44", MODE="0660"

  - hostname: talos-worker-02
    controlPlane: false
    ipAddress: 192.168.0.181
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false

  - hostname: talos-worker-03
    controlPlane: false
    ipAddress: 192.168.0.183
    installDisk: /dev/sda
    talosImageURL: factory.talos.dev/metal-installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba:v1.10.0
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "d0:50:99:a2:c5:4e"
        dhcp: false

patches:
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
