talosVersion: v1.10.0
kubernetesVersion: v1.33.0

clusterName: clB-cluster-b
endpoint: https://192.168.0.231:6443

clusterPodNets:
  - 10.16.0.0/16
clusterSvcNets:
  - 10.17.0.0/16

additionalApiServerCertSans:
  - 192.168.0.231
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.0.231
  - 127.0.0.1

nodes:
  - hostname: clB-cp01
    controlPlane: true
    ipAddress: 192.168.0.120
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:00:01"
        dhcp: false
        vip:
          ip: 192.168.0.231

  - hostname: clB-cp02
    controlPlane: true
    ipAddress: 192.168.0.121
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:00:02"
        dhcp: false
        vip:
          ip: 192.168.0.231

  - hostname: clB-cp03
    controlPlane: true
    ipAddress: 192.168.0.122
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:00:03"
        dhcp: false
        vip:
          ip: 192.168.0.231

  - hostname: clB-wk01
    controlPlane: false
    ipAddress: 192.168.0.123
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:10:01"
        dhcp: false
    patches:
      - |-
        machine:
          udev:
            rules:
              - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

  - hostname: clB-wk02
    controlPlane: false
    ipAddress: 192.168.0.124
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:10:02"
        dhcp: false

  - hostname: clB-wk03
    controlPlane: false
    ipAddress: 192.168.0.125
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "02:00:0A:01:10:03"
        dhcp: false

patches:
  - |-
    machine:
      network:
        nameservers:
          - 1.1.1.1
          - 1.0.0.1
  - |-
    machine:
      time:
        disabled: false
        servers: ["time.cloudflare.com"]

controlPlane:
  patches:
    - |-
      cluster:
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        network:
          cni:
            name: none
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0
